apiVersion: v1
kind: Namespace
metadata:
  name: mongo-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: mongo-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: mongo-namespace  
spec:
  ports:
    - port: 27017
  selector:
    app: mongo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: mongo-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

